version: '3'
services:
  app:
    build:
      context: .
    privileged: true
    environment:
      #- DISPLAY=${DISPLAY} linux
      - DISPLAY=host.docker.internal:0 # windovs, need https://sourceforge.net/projects/vcxsrv/ to work
    volumes:
      - . :/root/darknet/your_OC_dir
      - /tmp/.X11-unix:/tmp/.X11-unix